name: Deploy to AWS S3 and Lambda funtion

on:
 workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: | 
          aws s3 cp app/ s3://my-public-bucket-unique-name456/ --recursive --exclude "*" --include "*.html"
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ECR_URL }}:latest .
          docker push ${{ secrets.ECR_URL }}:latest

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name DemoLambdaFunction --image-uri ${{ secrets.ECR_URL }}:latest
