name: Deploy to AWS S3 and Lambda funtion

on:
 workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ECR_URL }}:$IMAGE_TAG .
          docker push ${{ secrets.ECR_URL }}:$IMAGE_TAG

      #- name: Deploy to AWS Lambda
      #  run: |
      #    aws lambda update-function-code --function-name $LAMBDA_FUNCTION --image-uri ${{ secrets.ECR_URL }}:$IMAGE_TAG