name: Terraform Deployment

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  setup-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Copy Terraform State File to S3
        run: |
          terraform init
          terraform apply -auto-approve
          #aws s3 cp terraform.tfstate s3://terraform-state-bucket-unique-name123/terraform.tfstate
