name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  setup-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        run: |
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform (Local Backend)
        run: terraform init

      - name: Apply Terraform to Create S3 & DynamoDB
        run: terraform apply -auto-approve

  store-state:
    needs: setup-infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        run: |
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Update Terraform Backend to Use S3
        run: |
          cat > backend.tf <<EOF
          terraform {
            backend "s3" {
              bucket         = "terraform-state-bucket-unique-name"
              key            = "terraform.tfstate"
              region         = "ap-south-1"
              dynamodb_table = "terraform-locks"
              encrypt        = true
            }
          }
          EOF

      - name: Reinitialize Terraform with S3 Backend
        run: terraform init -force-copy

      - name: Apply Terraform to Store State in S3
        run: terraform apply -auto-approve
